### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rkrishnan-arjun** [UBC-MDS/colourpycker#34]
Ensure the following fundamental changes are complete:

- [x] Deploy documentation rendered using the napoleon Sphinx extension at ReadTheDocs
- [x] Provide an example of how to use each function

Reference: https://pages.github.ubc.ca/mds-2022-23/DSCI_524_collab-sw-dev_students/materials/assignments/milestone3.html#documentation

**Comment by shaunhutch** [comment]
Finished this and opened a PR
