### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/colourpycker#42]
> **Congratulations on finishing milestone 2!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}

- [x] The documentation for the test functions is missing. - **quality -4**

#### 1. Create project structure for the R project
rubric={mechanics:20}

Well done!
   
## 3. R package function specifications
rubric={quality:10}

Well done!

## 4. Specific expectations for this milestone are:
rubric={mechanics:10}

Well done!

## 5. Submission instructions
rubric={mechanics:10}

- [x] The Python package and R package URL are missing  - **mechanics -2**

**Comment by lzung** [comment]
Thank you for the feedback!

I was hoping to ask about the documentation for our unit tests. We included documentation here for Milestone 2: https://github.com/UBC-MDS/colourpycker/blob/v1.0.0/tests/test_colourpycker.py

We were following the conventions in the tutorial (https://py-pkgs.org/05-testing#advanced-testing-methods). Is there an example for what documentation you were looking for?

**Comment by lzung** [comment]
Hi @negsadr, just following up on the above comment

**Comment by negsadr** [comment]
Hi @lzung 

Thanks for your message! You are right and I'm modifying your grade!

Good luck with the last week of the course!

**Comment by lzung** [comment]
@negsadr Thank you! :D
